/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author barki
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileButton = new javax.swing.JMenu();
        openButton = new javax.swing.JMenuItem();
        startButton = new javax.swing.JMenuItem();
        pauseButton = new javax.swing.JMenuItem();
        stopButton = new javax.swing.JMenuItem();
        exitButton = new javax.swing.JMenuItem();
        toolsButton = new javax.swing.JMenu();
        activityButton = new javax.swing.JMenu();
        preferencesButton = new javax.swing.JMenu();
        presetsButton = new javax.swing.JMenu();
        queueButton = new javax.swing.JMenu();
        showQueueButton = new javax.swing.JMenu();
        addQueueButton = new javax.swing.JMenu();
        helpButton = new javax.swing.JMenu();
        documentationButton = new javax.swing.JMenu();
        aboutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GearStick");

        fileButton.setText("File");

        openButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        openButton.setText("Open Source");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        fileButton.add(openButton);

        startButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        startButton.setText("Start Encode");
        fileButton.add(startButton);

        pauseButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        fileButton.add(pauseButton);

        stopButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        stopButton.setText("Stop");
        fileButton.add(stopButton);

        exitButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        exitButton.setText("Exit");
        fileButton.add(exitButton);

        menuBar.add(fileButton);

        toolsButton.setText("Tools");

        activityButton.setText("Activity Log");
        toolsButton.add(activityButton);

        preferencesButton.setText("Preferences");
        toolsButton.add(preferencesButton);

        menuBar.add(toolsButton);

        presetsButton.setText("Presets");
        menuBar.add(presetsButton);

        queueButton.setText("Queue");

        showQueueButton.setText("Show Queue");
        queueButton.add(showQueueButton);

        addQueueButton.setText("Add to Queue");
        queueButton.add(addQueueButton);

        menuBar.add(queueButton);

        helpButton.setText("Help");

        documentationButton.setText("Documentation");
        helpButton.add(documentationButton);

        aboutButton.setText("About ShiftStick");
        helpButton.add(aboutButton);

        menuBar.add(helpButton);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pauseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutButton;
    private javax.swing.JMenu activityButton;
    private javax.swing.JMenu addQueueButton;
    private javax.swing.JMenu documentationButton;
    private javax.swing.JMenuItem exitButton;
    private javax.swing.JMenu fileButton;
    private javax.swing.JMenu helpButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openButton;
    private javax.swing.JMenuItem pauseButton;
    private javax.swing.JMenu preferencesButton;
    private javax.swing.JMenu presetsButton;
    private javax.swing.JMenu queueButton;
    private javax.swing.JMenu showQueueButton;
    private javax.swing.JMenuItem startButton;
    private javax.swing.JMenuItem stopButton;
    private javax.swing.JMenu toolsButton;
    // End of variables declaration//GEN-END:variables
}
