/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author barki, ilkergzlkkr
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        summaryPanel = new javax.swing.JPanel();
        formatLabel = new javax.swing.JLabel();
        formatCBox = new javax.swing.JComboBox<>();
        tracksLabel = new javax.swing.JLabel();
        filtersLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        previewLabel = new javax.swing.JLabel();
        previewWindow = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        sizeTextBox = new javax.swing.JTextField();
        filtersTextBox = new javax.swing.JTextField();
        tracksTextPanel = new javax.swing.JTextPane();
        dimensionsPanel = new javax.swing.JPanel();
        filtersPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        videoPanel = new javax.swing.JPanel();
        videoEncoderLabel = new javax.swing.JLabel();
        encoderComboBox = new javax.swing.JComboBox<>();
        framerateComboBox = new javax.swing.JComboBox<>();
        framerateLabel = new javax.swing.JLabel();
        qualitySlider = new javax.swing.JSlider();
        qualityLabel = new javax.swing.JLabel();
        advancedOptionsLabel = new javax.swing.JLabel();
        advancedOptionsTextPane = new javax.swing.JTextPane();
        hardwareAccelerationComboBox = new javax.swing.JCheckBox();
        constantFramerateComboBox = new javax.swing.JCheckBox();
        peakFramerateComboBox = new javax.swing.JCheckBox();
        audioPanel = new javax.swing.JPanel();
        presetLabel = new javax.swing.JLabel();
        presetComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        saveLabel = new javax.swing.JLabel();
        saveTextBox = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();
        reloadBtn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openBtn = new javax.swing.JMenuItem();
        startBtn = new javax.swing.JMenuItem();
        pauseBtn = new javax.swing.JMenuItem();
        stopBtn = new javax.swing.JMenuItem();
        exitBtn = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        activityButton = new javax.swing.JMenuItem();
        preferencesButton = new javax.swing.JMenuItem();
        presetsMenu = new javax.swing.JMenu();
        managePresetsBtn = new javax.swing.JMenuItem();
        savePresetBtn = new javax.swing.JMenuItem();
        deletePresetBtn = new javax.swing.JMenuItem();
        importPresetBtn = new javax.swing.JMenuItem();
        exportPresetsBtn = new javax.swing.JMenuItem();
        queueButton = new javax.swing.JMenu();
        queueBtn = new javax.swing.JMenuItem();
        addQueueBtn = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GearStick");

        mainTabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        formatLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formatLabel.setText("Format:");

        formatCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MP4", "MKV", "WebM", "GIF" }));

        tracksLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tracksLabel.setText("Tracks:");

        filtersLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filtersLabel.setText("Filters:");

        sizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sizeLabel.setText("Size:");

        previewLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        previewLabel.setText("Preview:");

        previewWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dummy_512x288_ffffff_cccccc.png"))); // NOI18N

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backButton.setText("<");

        forwardButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        forwardButton.setText(">");
        forwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sizeLabel)
                            .addComponent(filtersLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formatLabel)
                            .addComponent(tracksLabel))
                        .addGap(20, 20, 20)
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(summaryPanelLayout.createSequentialGroup()
                                .addComponent(formatCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createSequentialGroup()
                                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(filtersTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(tracksTextPanel)
                                    .addComponent(sizeTextBox))
                                .addGap(39, 39, 39)))
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(previewWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previewLabel))
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formatCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(previewLabel)))
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tracksLabel)
                            .addComponent(tracksTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtersTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtersLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sizeLabel)
                            .addComponent(sizeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previewWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(forwardButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Summary", summaryPanel);

        javax.swing.GroupLayout dimensionsPanelLayout = new javax.swing.GroupLayout(dimensionsPanel);
        dimensionsPanel.setLayout(dimensionsPanelLayout);
        dimensionsPanelLayout.setHorizontalGroup(
            dimensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        dimensionsPanelLayout.setVerticalGroup(
            dimensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Dimensions", dimensionsPanel);

        jLabel1.setText("Detelecine:");

        jLabel2.setText("Denoise:");

        jLabel3.setText("Sharpen:");

        jLabel4.setText("Deinterlace:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout filtersPanelLayout = new javax.swing.GroupLayout(filtersPanel);
        filtersPanel.setLayout(filtersPanelLayout);
        filtersPanelLayout.setHorizontalGroup(
            filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtersPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(filtersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filtersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filtersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(filtersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(756, Short.MAX_VALUE))
        );
        filtersPanelLayout.setVerticalGroup(
            filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtersPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Filters", filtersPanel);

        videoEncoderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        videoEncoderLabel.setText("Video Encoder:");

        encoderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H.264", "H.265", "AV1" }));

        framerateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24", "30", "60", "120" }));
        framerateComboBox.setSelectedIndex(1);

        framerateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        framerateLabel.setText("Framerate:");

        qualitySlider.setMajorTickSpacing(5);
        qualitySlider.setMaximum(50);
        qualitySlider.setMinorTickSpacing(1);
        qualitySlider.setPaintTicks(true);
        qualitySlider.setSnapToTicks(true);
        qualitySlider.setValue(25);

        qualityLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qualityLabel.setText("Quality:");

        advancedOptionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        advancedOptionsLabel.setText("Advanced Options:");

        hardwareAccelerationComboBox.setText("Hardware Acceleration");

        constantFramerateComboBox.setSelected(true);
        constantFramerateComboBox.setText("Constant Framerate");

        peakFramerateComboBox.setText("Peak Framerate");

        javax.swing.GroupLayout videoPanelLayout = new javax.swing.GroupLayout(videoPanel);
        videoPanel.setLayout(videoPanelLayout);
        videoPanelLayout.setHorizontalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(videoPanelLayout.createSequentialGroup()
                        .addComponent(advancedOptionsLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(videoPanelLayout.createSequentialGroup()
                        .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(advancedOptionsTextPane)
                            .addGroup(videoPanelLayout.createSequentialGroup()
                                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(videoPanelLayout.createSequentialGroup()
                                            .addComponent(framerateLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(framerateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(videoPanelLayout.createSequentialGroup()
                                            .addComponent(videoEncoderLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(encoderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(hardwareAccelerationComboBox)
                                    .addComponent(constantFramerateComboBox)
                                    .addComponent(peakFramerateComboBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qualityLabel)
                                    .addComponent(qualitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))))
        );
        videoPanelLayout.setVerticalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(videoEncoderLabel)
                    .addComponent(encoderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qualityLabel))
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(videoPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(qualitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(videoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hardwareAccelerationComboBox)))
                .addGap(16, 16, 16)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(framerateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(framerateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(constantFramerateComboBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peakFramerateComboBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(advancedOptionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advancedOptionsTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        mainTabbedPane.addTab("Video", videoPanel);

        javax.swing.GroupLayout audioPanelLayout = new javax.swing.GroupLayout(audioPanel);
        audioPanel.setLayout(audioPanelLayout);
        audioPanelLayout.setHorizontalGroup(
            audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        audioPanelLayout.setVerticalGroup(
            audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Audio", audioPanel);

        presetLabel.setText("Preset: ");

        presetComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Slow", "Fast", "Very Fast" }));

        jButton1.setText("Start Encode");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        saveLabel.setText("Save As:");

        saveTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTextBoxActionPerformed(evt);
            }
        });

        browseBtn.setText("Browse");

        reloadBtn.setText("Reload");

        fileMenu.setText("File");

        openBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        openBtn.setText("Open Source");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });
        fileMenu.add(openBtn);

        startBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        startBtn.setText("Start Encode");
        fileMenu.add(startBtn);

        pauseBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        pauseBtn.setText("Pause");
        pauseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseBtnActionPerformed(evt);
            }
        });
        fileMenu.add(pauseBtn);

        stopBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        stopBtn.setText("Stop");
        fileMenu.add(stopBtn);

        exitBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        exitBtn.setText("Exit");
        fileMenu.add(exitBtn);

        menuBar.add(fileMenu);

        toolsMenu.setText("Tools");

        activityButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        activityButton.setText("Activity Log");
        toolsMenu.add(activityButton);

        preferencesButton.setText("Preferences");
        toolsMenu.add(preferencesButton);

        menuBar.add(toolsMenu);

        presetsMenu.setText("Presets");

        managePresetsBtn.setText("Manage Presets");
        managePresetsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePresetsBtnActionPerformed(evt);
            }
        });
        presetsMenu.add(managePresetsBtn);

        savePresetBtn.setText("Save New Preset");
        presetsMenu.add(savePresetBtn);

        deletePresetBtn.setText("Delete Preset");
        presetsMenu.add(deletePresetBtn);

        importPresetBtn.setText("Import from File");
        presetsMenu.add(importPresetBtn);

        exportPresetsBtn.setText("Export to File");
        presetsMenu.add(exportPresetsBtn);

        menuBar.add(presetsMenu);

        queueButton.setText("Queue");

        queueBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        queueBtn.setText("Queue");
        queueButton.add(queueBtn);

        addQueueBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addQueueBtn.setText("Add to Queue");
        queueButton.add(addQueueBtn);

        menuBar.add(queueButton);

        helpMenu.setText("Help");

        helpBtn.setText("About GearStick");
        helpMenu.add(helpBtn);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(presetLabel)
                        .addGap(18, 18, 18)
                        .addComponent(presetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reloadBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveTextBox)
                        .addGap(18, 18, 18)
                        .addComponent(browseBtn)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(presetLabel)
                            .addComponent(presetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reloadBtn))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)))
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveLabel)
                    .addComponent(saveTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forwardButtonActionPerformed

    private void saveTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveTextBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_openBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_openBtnActionPerformed

    private void pauseBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pauseBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pauseBtnActionPerformed

    private void managePresetsBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_managePresetsBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_managePresetsBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem activityButton;
    private javax.swing.JMenuItem addQueueBtn;
    private javax.swing.JLabel advancedOptionsLabel;
    private javax.swing.JTextPane advancedOptionsTextPane;
    private javax.swing.JPanel audioPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton browseBtn;
    private javax.swing.JCheckBox constantFramerateComboBox;
    private javax.swing.JMenuItem deletePresetBtn;
    private javax.swing.JPanel dimensionsPanel;
    private javax.swing.JComboBox<String> encoderComboBox;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JMenuItem exportPresetsBtn;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel filtersLabel;
    private javax.swing.JPanel filtersPanel;
    private javax.swing.JTextField filtersTextBox;
    private javax.swing.JComboBox<String> formatCBox;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JButton forwardButton;
    private javax.swing.JComboBox<String> framerateComboBox;
    private javax.swing.JLabel framerateLabel;
    private javax.swing.JCheckBox hardwareAccelerationComboBox;
    private javax.swing.JMenuItem helpBtn;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem importPresetBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JMenuItem managePresetsBtn;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openBtn;
    private javax.swing.JMenuItem pauseBtn;
    private javax.swing.JCheckBox peakFramerateComboBox;
    private javax.swing.JMenuItem preferencesButton;
    private javax.swing.JComboBox<String> presetComboBox;
    private javax.swing.JLabel presetLabel;
    private javax.swing.JMenu presetsMenu;
    private javax.swing.JLabel previewLabel;
    private javax.swing.JLabel previewWindow;
    private javax.swing.JLabel qualityLabel;
    private javax.swing.JSlider qualitySlider;
    private javax.swing.JMenuItem queueBtn;
    private javax.swing.JMenu queueButton;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JLabel saveLabel;
    private javax.swing.JMenuItem savePresetBtn;
    private javax.swing.JTextField saveTextBox;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTextField sizeTextBox;
    private javax.swing.JMenuItem startBtn;
    private javax.swing.JMenuItem stopBtn;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JLabel tracksLabel;
    private javax.swing.JTextPane tracksTextPanel;
    private javax.swing.JLabel videoEncoderLabel;
    private javax.swing.JPanel videoPanel;
    // End of variables declaration//GEN-END:variables
}
