/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author barki
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openBtn = new javax.swing.JMenuItem();
        startBtn = new javax.swing.JMenuItem();
        pauseBtn = new javax.swing.JMenuItem();
        stopBtn = new javax.swing.JMenuItem();
        exitBtn = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        activityButton = new javax.swing.JMenuItem();
        preferencesButton = new javax.swing.JMenuItem();
        presetsMenu = new javax.swing.JMenu();
        presetsSubBtn = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        managePresetsBtn = new javax.swing.JMenuItem();
        savePresetBtn = new javax.swing.JMenuItem();
        deletePresetBtn = new javax.swing.JMenuItem();
        importPresetBtn = new javax.swing.JMenuItem();
        exportPresetsBtn = new javax.swing.JMenuItem();
        queueButton = new javax.swing.JMenu();
        queueBtn = new javax.swing.JMenuItem();
        addQueueBtn = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GearStick");

        fileMenu.setText("File");

        openBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        openBtn.setText("Open Source");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });
        fileMenu.add(openBtn);

        startBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        startBtn.setText("Start Encode");
        fileMenu.add(startBtn);

        pauseBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        pauseBtn.setText("Pause");
        pauseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseBtnActionPerformed(evt);
            }
        });
        fileMenu.add(pauseBtn);

        stopBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        stopBtn.setText("Stop");
        fileMenu.add(stopBtn);

        exitBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        exitBtn.setText("Exit");
        fileMenu.add(exitBtn);

        menuBar.add(fileMenu);

        toolsMenu.setText("Tools");

        activityButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        activityButton.setText("Activity Log");
        toolsMenu.add(activityButton);

        preferencesButton.setText("Preferences");
        toolsMenu.add(preferencesButton);

        menuBar.add(toolsMenu);

        presetsMenu.setText("Presets");

        presetsSubBtn.setText("Presets");

        jMenuItem1.setText("Default");
        presetsSubBtn.add(jMenuItem1);

        presetsMenu.add(presetsSubBtn);

        managePresetsBtn.setText("Manage Presets");
        managePresetsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePresetsBtnActionPerformed(evt);
            }
        });
        presetsMenu.add(managePresetsBtn);

        savePresetBtn.setText("Save New Preset");
        presetsMenu.add(savePresetBtn);

        deletePresetBtn.setText("Delete Preset");
        presetsMenu.add(deletePresetBtn);

        importPresetBtn.setText("Import from File");
        presetsMenu.add(importPresetBtn);

        exportPresetsBtn.setText("Export to File");
        presetsMenu.add(exportPresetsBtn);

        menuBar.add(presetsMenu);

        queueButton.setText("Queue");

        queueBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        queueBtn.setText("Queue");
        queueButton.add(queueBtn);

        addQueueBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addQueueBtn.setText("Add to Queue");
        queueButton.add(addQueueBtn);

        menuBar.add(queueButton);

        helpMenu.setText("Help");

        helpBtn.setText("About ShiftStick");
        helpMenu.add(helpBtn);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openBtnActionPerformed

    private void pauseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pauseBtnActionPerformed

    private void managePresetsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePresetsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managePresetsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem activityButton;
    private javax.swing.JMenuItem addQueueBtn;
    private javax.swing.JMenuItem deletePresetBtn;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JMenuItem exportPresetsBtn;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem helpBtn;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem importPresetBtn;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem managePresetsBtn;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openBtn;
    private javax.swing.JMenuItem pauseBtn;
    private javax.swing.JMenuItem preferencesButton;
    private javax.swing.JMenu presetsMenu;
    private javax.swing.JMenu presetsSubBtn;
    private javax.swing.JMenuItem queueBtn;
    private javax.swing.JMenu queueButton;
    private javax.swing.JMenuItem savePresetBtn;
    private javax.swing.JMenuItem startBtn;
    private javax.swing.JMenuItem stopBtn;
    private javax.swing.JMenu toolsMenu;
    // End of variables declaration//GEN-END:variables
}
